server:
  port: 8080

spring:
  application:
    name: gateway-service
  
  cloud:
    gateway:
      # Rutas configuradas programáticamente en GatewayConfig.java
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 3600
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

  security:
    oauth2:
      resourceserver:
        jwt:
          # Configuración para Keycloak
          issuer-uri: http://localhost:8180/realms/acceso-tabasco
          jwk-set-uri: http://localhost:8180/realms/acceso-tabasco/protocol/openid-connect/certs

# Configuración de Keycloak
keycloak:
  realm: acceso-tabasco
  auth-server-url: http://localhost:8180
  ssl-required: none
  resource: gateway-client
  credentials:
    secret: your-client-secret
  use-resource-role-mappings: true
  bearer-only: true

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: when-authorized

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.reactive: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Gateway specific configuration
# Configuración específica de gateway (no deprecated)
app:
  gateway:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:4200
    security:
      public-paths:
        - /actuator/**
        - /public/**
        - /auth/login
        - /auth/register
