# Configuración común para todos los servicios
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# Configuración de Eureka común
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Configuración de Keycloak común
keycloak:
  realm: gobierno-tabasco
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8180}

# Configuración de gobierno de Tabasco
tabasco:
  gov:
    sistema:
      nombre: "Sistema de Acceso Unificado"
      version: "1.0.0"
    dependencia:
      responsable: "CGMAIG"
      contacto: "soporte-acceso@tabasco.gob.mx"
    nomina:
      validation:
        required-status: "ACTIVO"

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info

---
# Configuración para DESARROLLO
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    saf.cgmaig: DEBUG
    root: INFO

keycloak:
  auth-server-url: http://localhost:8180

---
# Configuración para PRODUCCIÓN
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    saf.cgmaig: INFO
    root: WARN

keycloak:
  auth-server-url: https://auth.tabasco.gob.mx