# Configuración para Auth Service
server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/acceso_tabasco}
    username: ${DB_USER:auth_user}
    password: ${DB_PASSWORD:auth_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/gobierno-tabasco}

# Vista de nómina
nomina:
  view:
    name: vw_empleados_nomina
  validation:
    required-status: ACTIVO

---
# Configuración para DESARROLLO
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    saf.cgmaig: DEBUG

---
# Configuración para PRODUCCIÓN
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    saf.cgmaig: INFO