# Configuración para Gateway Service
server:
  port: 8080

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/gobierno-tabasco}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/gobierno-tabasco/protocol/openid-connect/certs}

---
# Configuración para DESARROLLO
spring:
  config:
    activate:
      on-profile: dev

---
# Configuración para PRODUCCIÓN
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8080