# Configuración para User Service
server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/acceso_tabasco}
    username: ${DB_USER:user_service}
    password: ${DB_PASSWORD:user_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/gobierno-tabasco}

# Configuración CURP
user:
  curp:
    validation:
      enabled: true

---
# Configuración para DESARROLLO
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    saf.cgmaig.user: DEBUG

---
# Configuración para PRODUCCIÓN
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    saf.cgmaig.user: INFO